### ISSUE TITLE
About the secluded example

### ISSUE THREAD

**Issue by LeonKLK** [icecube/charon#1]
Dear developers,

My name is Leon and I am trying to use your secluded example(example_secluded.ipynb) to compute some results for my project. 
However, when I try to run it, there is a error message staying that `TabError: inconsistent use of tabs and spaces in indentation` in your `propa.py`. As suggested by the statement itself, the problem could be the misuse of `tab` and `space` for indentation. And this happens in some lines of code.
Right now I am trying to fix it one by one until I can import `propa` probably. 
You may read [https://stackoverflow.com/questions/5685406/inconsistent-use-of-tabs-and-spaces-in-indentation](url) for more detailed explanation. 

Best regards,
Leon

**Comment by qrliu** [comment]
The format should be fixed now.
